pod 'RDVTabBarController', '~> 1.1.9'
pod 'LXMButtonImagePosition', '~> 1.1.1'
pod 'Masonry', '~> 1.0.0'
pod 'SDCycleScrollView','~> 1.64'
pod 'MJRefresh', '~> 3.1.0'
pod 'AFNetworking', '~> 3.1.0'
pod 'ARSegmentPager', '~> 1.1.2'
pod 'HMSegmentedControl', '~> 1.5.2'
pod "ZWSlideViewController"

